spring.application.name=notificacoes-service
server.port=8082

spring.mongodb.uri=${NOTIFICACOES_MONGODB_URI:mongodb://notificacoes_admin:notificacoes_password@localhost:27017/notificacoes_db?authSource=admin}
spring.data.mongodb.auto-index-creation=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health